{% set name = "diraccfg" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a42a2f7436c9f5d0ea21807013db55e5e8797f135cb6c9891863abeadd127434

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - diraccfg = diraccfg.__main__:parseArgs

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - six

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - diraccfg
  commands:
    - pytest -v

about:
  home: https://github.com/DIRACGrid/diraccfg
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: DIRAC stand-alone cfg files parser
  description: |
    diraccfg provides a parser for the configuration files used by
    [DIRAC](https://github.com/DIRACGrid/DIRAC/) and its associated projects.
    It is designed to be usable as either a full Python package or as a
    standalone file, which can be found in src/diraccfg/cfg.py. The standalone
    mode allows for this to be used by dirac-install and the pilot scripts
    without requiring of pip.
  dev_url: https://github.com/DIRACGrid/diraccfg

extra:
  recipe-maintainers:
    - chrisburr
